name = "hex-row-reduce-mathlib"
defaultTargets = ["HexRowReduceMathlib"]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "f1580d28c2e9ff9e8d4d7cdef9dccbaa17780b03"

[[require]]
name = "HexRowReduce"
git = "https://github.com/leanprover/hex-row-reduce.git"
rev = "176a31945c321d8268d5b340851d98b8f1bc7c8d"

[[require]]
name = "HexMatrixMathlib"
git = "https://github.com/leanprover/hex-matrix-mathlib.git"
rev = "9ccf1baf235ae8fe10733a279cffa96ff28236dd"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.0-rc1-patch1"

[[lean_lib]]
name = "HexRowReduceMathlib"
