name = "hex-row-reduce-mathlib"
defaultTargets = ["HexRowReduceMathlib"]

[[require]]
name = "HexBasic"
git = "https://github.com/kim-em/hex-basic.git"
rev = "c9cb6bcb3287ea0870f66c9dfcba08baa08f97f6"

[[require]]
name = "HexRowReduce"
git = "https://github.com/kim-em/hex-row-reduce.git"
rev = "30839abafa39e1a93ddc1e586a3d57e2f4daa0c6"

[[require]]
name = "HexMatrixMathlib"
git = "https://github.com/kim-em/hex-matrix-mathlib.git"
rev = "fd01fba69095034c7ee992c488017bd9da1b94a9"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.0-rc1-patch1"

[[lean_lib]]
name = "HexRowReduceMathlib"
