name = "hex-row-reduce-mathlib"
defaultTargets = ["HexRowReduceMathlib"]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "f1580d28c2e9ff9e8d4d7cdef9dccbaa17780b03"

[[require]]
name = "HexRowReduce"
git = "https://github.com/leanprover/hex-row-reduce.git"
rev = "a5b4db02cadc7a1e60e2ae7e085cb6facf415ee0"

[[require]]
name = "HexMatrixMathlib"
git = "https://github.com/leanprover/hex-matrix-mathlib.git"
rev = "be15f40e4942fe78ed28f037c9407a94bc3c10ce"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.0-rc1-patch1"

[[lean_lib]]
name = "HexRowReduceMathlib"
